engines:
  phpmd:
    enabled: true
    checks:
      CleanCode/ElseExpression:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Naming/LongVariable:
        enabled: false
        
  fixme:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
      - php:

ratings:
  paths:
  - src/**

exclude_paths:
- "phpdocs/"
- "tests/"
- "test/"
- "vendor/"
- "wiki/"